# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

commextr <- function(d, ps, x, rest, vb) {
    .Call('_MODifieR_commextr', PACKAGE = 'MODifieR', d, ps, x, rest, vb)
}

